mywebsite/about/urls.py
from . import views 
from django.urls import path 

urlpatterns = [
    path('', views.check)
]

mywebsite/blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('post/', views.post_list, name='post_list'),
    path('comment/', views.comment_list, name='comment_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

mywebsite/mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from . import views

def index(request):
    return HttpResponse('test')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('views/', views.viewer),
    path('test/', include('about.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
]

mywebsite/about/models.py
from django.db import models

# Create your models here.

mywebsite/blog/models.py
from django.db import models
from django.db.models.fields import CharField, EmailField, TextField
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

#query manager
class PublishManager(models.Manager):
    def get_queryset(self):
        return super(PublishManager, self).get_queryset().filter(status='published')

# Create your models here.
class Post(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')

    
    object = models.Manager()
    published = PublishManager()
    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

class CommentManager(models.Manager):
    def get_queryset(self):
        return super(CommentManager, self).get_queryset().filter(active=True)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    nama = models.CharField(max_length=80)
    email = models.EmailField(max_length=255)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    object = models.Manager()
    publishing = CommentManager()

    class Meta: 
        ordering = ('created',)
    
    def __str__(self):
        return f"Komentar ditulis oleh {self.nama} di {self.post}!"

# Create your models here.

mywebsite/blog/forms.py
from django import forms
from .models import Comment

#inheritance class Form
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('nama', 'email', 'body')
        

mywebsite/about/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def check(request):
    return render(request,'test.html')

mywebsite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator,  PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse

# Create your views here.
def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} Pesan django" \
                        f"{post.title}"
            message = f"Membagikan {post.title} di alamat {post_url}\n\n" \
                        f"{cd['name']}\'s comments: {cd['comments']}"
            try:
                send_mail(subject, message, 'akhmadfaizal13@gmail.com', [cd['to']], fail_silently=False)
                sent = True
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            
        else:
            form = EmailPostForm()
        return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent':sent})
    return render(request, 'blog/post/share.html')

def post_list(request):
    obj = Post.published.all()
    paginator= Paginator(obj, 4)
    page = request.GET.get('page')
    try:
    	post = paginator.page(page)
    except PageNotAnInteger:
    	post = paginator.page(1)
    except:
    	post = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': post, 'page': page})

def comment_list(request):
    comment = Comment.publishing.all()
    return render(request, 'blog/comment/comment.html', {'comments': comment})

def post_detail(request, year, month, day, post):
    posts = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    comments = posts.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = posts
            new_comment.save()
        else:
            comment_form = CommentForm()
        return render(request, 'blog/post/detail.html',{'post': posts,'comments': comments,'new_comment': new_comment,'comment_form': comment_form})
    return render(request, 'blog/post/detail.html',{'post': posts})

mywebsite/mywebsite/views.py
from django.http import HttpResponse

def viewer(request):
    return HttpResponse('views')

mywebsite/about/templates/test.html
<!DOCTYPE html>
<html>
    <head>
        <title>Test</title>
    </head>
    <body>
        <h2>Test</h2>
    </body>
</html>

mywebsite/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>{%block title%}{%endblock%}</title>
        <link rel='stylesheet' href="{% static 'css/blog.css' %}"/>
    </head>
    <body>
        <div>
            {%block content%}{%endblock%}
        </div>
    </body>
</html>

mywebsite/templates/blog/comment/comment.html
{%extends 'blog/base.html' %}
{% block title %}Comment blog {% endblock %} 
{%block content %}
    {% for comment in comments%}
        <h2 id='content'>{{comment.post}}</h2>
        <h4>komentarnya: {{comment.body}}</h4>
        <p>nama komentator: {{comment.nama}}</p>
        <p>dibuat pada {{comment.created}}</p>
        <p>status : {{comment.active}}</p>
    {% endfor %}
{%endblock%}

mywebsite/templates/blog/pagination.html
{% extends 'blog/base.html' %}
{%block title%}Read Data{%endblock%}
{%block content%}
<div class='pagination'>
	<span class='step-links'>
		{% if page.has_previous %}
			<a href='?page={{page.previous_page_number}}'>Sebelumnya</a>
		{% endif %}
		<p class='current'>halaman {{page.number}} dari {{page.paginator.num_pages}}</p>
		{% if page.has_next %}
			<a href='?page={{page.next_page_number}}'>selanjutnya</a>
		{% endif %}
	</span>
</div>
{% endblock %}

mywebsite/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{%block title%}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class='date'>
        Published {{ post.publish}} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <a href="{% url 'blog:post_share' post.id%}">Bagikan</a>

    {% with comments.count as total_comments %}
        {{ total_comments }} comment {{ total_comments|pluralize}}
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.nama }}
                {{ comment.created }}
            </p>
        {{ comment.body|linebreaks }}
        </div>
        {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

mywebsite/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{%block title%}Read Data{%endblock%}
{%block content%}
    {%for post in posts %}
        <a href='{{post.get_absolute_url}}'>{{post.title}}</a>
        <p>Published: {{post.publish}} by {{ post.author}}</p>
        <p>{{post.body|truncatewords:30|linebreaks}}</p>
    {%endfor%}
    {% include 'blog/pagination.html' with page=posts %}
{%endblock%}

mywebsite/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}Share email {% endblock %}
{% block content %}
    {% if sent %}
        <h1>Pesan berhasil di kirim :) </h1>
        <p>
            {{post.title}} berhasil dikirimkan ke {{ form.cleaned_data.to }}
        </p>
    {% else %}
        <h1>Share {{post.title}}  by email</h1>
        <form method='POST'>
            {% csrf_token %}
            {{form.as_p}}
            <input type='submit' value='kirim email'/>
        </form>
    {% endif %}
{% endblock %}